version: '3.3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    restart: unless-stopped

  app:
    build: ./fastapi-app
    container_name: app
    expose:
      - "8000"
    environment:
      - MASTER_URL=postgresql://appuser:apppassword@postgres-master/appdb
      - REPLICA_URL=postgresql://appuser:apppassword@postgres-replica/appdb
    restart: unless-stopped
    depends_on:
      - postgres-1
      - postgres-2

  postgres-1:
    image: docker.io/bitnamilegacy/postgresql-repmgr:17.6.0
    container_name: postgres-master
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=password
      - POSTGRESQL_USERNAME=appuser
      - POSTGRESQL_PASSWORD=apppassword
      - POSTGRESQL_DATABASE=appdb
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=postgres-1
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_PARTNER_NODES=postgres-1:5432,postgres-2:5432
      - REPMGR_NODE_NAME=postgres-1
      - REPMGR_NODE_NETWORK_NAME=postgres-1
      - REPMGR_PORT_NUMBER=5432
      - REPMGR_CONNECT_TIMEOUT=1
      - REPMGR_RECONNECT_ATTEMPTS=2
      - REPMGR_RECONNECT_INTERVAL=1
      - REPMGR_MASTER_RESPONSE_TIMEOUT=5
      - REPMGR_NODE_ID=1
    volumes:
      - postgres_master_data:/bitnami/postgresql
      - ./postgres/init-db.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped

  postgres-2:
    image: docker.io/bitnamilegacy/postgresql-repmgr:17.6.0
    container_name: postgres-replica
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=password
      - POSTGRESQL_USERNAME=appuser
      - POSTGRESQL_PASSWORD=apppassword
      - POSTGRESQL_DATABASE=appdb
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=postgres-1
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_PARTNER_NODES=postgres-1:5432,postgres-2:5432
      - REPMGR_NODE_NAME=postgres-2
      - REPMGR_NODE_NETWORK_NAME=postgres-2
      - REPMGR_PORT_NUMBER=5432
      - REPMGR_CONNECT_TIMEOUT=1
      - REPMGR_RECONNECT_ATTEMPTS=2
      - REPMGR_RECONNECT_INTERVAL=1
      - REPMGR_MASTER_RESPONSE_TIMEOUT=5
      - REPMGR_NODE_ID=2
    volumes:
      - postgres_replica_data:/bitnami/postgresql
    restart: unless-stopped

  pg_exporter_master:
    container_name: pg_exporter_master
    image: prometheuscommunity/postgres-exporter:v0.18.1
    command: --log.level=debug
    environment:
      DATA_SOURCE_URI: "postgres-1:5432/appdb?sslmode=disable"
      DATA_SOURCE_USER: "appuser"
      DATA_SOURCE_PASS: "apppassword"
      PG_EXPORTER_EXTEND_QUERY_PATH: "/etc/postgres_exporter/queries.yaml"
    volumes:
      - ./postgres_exporter/queries.yaml:/etc/postgres_exporter/queries.yaml:ro
    ports:
      - "9187:9187"
    restart: unless-stopped
    depends_on:
      - postgres-1

  pg_exporter_replica:
    container_name: pg_exporter_replica
    image: prometheuscommunity/postgres-exporter:v0.18.1
    command: --log.level=debug
    environment:
      DATA_SOURCE_URI: "postgres-2:5432/appdb?sslmode=disable"
      DATA_SOURCE_USER: "appuser"
      DATA_SOURCE_PASS: "apppassword"
      PG_EXPORTER_EXTEND_QUERY_PATH: "/etc/postgres_exporter/queries.yaml"
    volumes:
      - ./postgres_exporter/queries.yaml:/etc/postgres_exporter/queries.yaml:ro
    ports:
      - "9188:9187"
    restart: unless-stopped
    depends_on:
      - postgres-2

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /cgroup:/cgroup:ro
    ports:
      - "8081:8080"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  postgres_master_data:
  postgres_replica_data:
  prometheus_data:
  grafana_data: