global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'postgres_master'
    static_configs:
      - targets: ['pg_exporter_master:9187']
    params:
      collect[]:
        - standard
        - database_size
        - replication

  - job_name: 'postgres_replica'
    static_configs:
      - targets: ['pg_exporter_replica:9187']
    params:
      collect[]:
        - standard
        - database_size
        - replication

  - job_name: 'container_cpu'
    static_configs:
      - targets: ['cadvisor:8080']