global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'datetime-service'
    static_configs:
      - targets: ['datetime-service:8000']
    scrape_interval: 5s
    metrics_path: '/metrics'